name: Setup Sphynx
author: Pedro Rodrigues
description: Set up Sphynx CLI.
branding:
  icon: award
  color: gray-dark
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869 # master
    - name: Install Sphynx
      run: brew install hpedrorodrigues/tools/sphynx
      shell: sh
