name: Setup Sphynx
author: Pedro Rodrigues
description: Set up Sphynx CLI.
branding:
  icon: award
  color: gray-dark
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@9651e3cfa42dae9ae90ca79eaa6d36dcd8569168 # master
    - name: Install Sphynx
      run: brew install hpedrorodrigues/tools/sphynx
      shell: sh
