name: Setup Sphynx
author: Pedro Rodrigues
description: Set up Sphynx CLI.
branding:
  icon: award
  color: gray-dark
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@b76d5417896401ff5eb699ab8b1bf8948b001ce8 # master
    - name: Install Sphynx
      run: brew install hpedrorodrigues/tools/sphynx
      shell: sh
