name: kustomize
author: Pedro Rodrigues
description: Simple action to validate kustomization files and outputs.
inputs:
  detection:
    description: Strategy to to use to detect kustomization directories.
    required: true
  path:
    description: Paths to kustomization directories.
    required: false
    default: ''
  log_level:
    description: Log level to use.
    required: false
    default: 'quiet'
branding:
  icon: 'rotate-cw'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> "${GITHUB_PATH}"
      shell: sh
    - run: entrypoint.sh
      shell: sh
