apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:latest
          command:
            - /app
            - --port=8080
            - --verbose=$(VERBOSE)
            - --debug=$(DEBUG)
          ports:
            - containerPort: 8080
          env:
            - name: VERBOSE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: verbose
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: debug
