apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app
labels:
  - includeSelectors: true
    pairs:
      app: app
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
