name: envsubst
author: Pedro Rodrigues
description: simple action to run envsubst on a file
inputs:
  template_file:
    description: Template file to process substitutions on
    required: true
  result_file:
    description: Result file with substitutions applied
    required: true
branding:
  icon: 'rotate-cw'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
