name: envsubst
author: Pedro Rodrigues
description: Simple wrapper action for envsubst.
inputs:
  input:
    description: One or more template files to process substitutions on (separated by space).
    required: true
  output:
    description: One or more result files with substitutions applied (separated by space).
    required: true
branding:
  icon: 'rotate-cw'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
