name: envsubst
author: Pedro Rodrigues
description: simple action to run envsubst on a file
inputs:
  template:
    description: One or more template files to process substitutions on (separated by space).
    required: true
  result:
    description: One or more result files with substitutions applied (separated by space).
    required: true
branding:
  icon: 'rotate-cw'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
