name: envsubst
author: Pedro Rodrigues
description: Simple wrapper action for envsubst.
inputs:
  input:
    description: One or more input files to apply substitutions to (separated by space).
    required: true
  output:
    description: One or more output files to write the result to (separated by space).
    required: false
    default: ''
  in_place:
    description: Whether to apply the substitutions in place.
    required: false
    default: false
  format:
    description: Restrict the substitutions to the environment variables referenced in the format string.
    required: false
    default: ''
branding:
  icon: 'rotate-cw'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
