name: tools
author: Pedro Rodrigues
description: Let you run a few pre-installed Linux tools without the necessity to install them on the runner.
inputs:
  script:
    description: Shell script to run inside the container.
    required: true
branding:
  icon: activity
  color: gray-dark
runs:
  using: docker
  image: Dockerfile
