name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0
      - name: Run tests
        run: bats --print-output-on-failure --timing --recursive .
        shell: sh
