name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shell-actions-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: 1.14.0
      - name: Run tests
        run: bats --print-output-on-failure --timing --recursive .
        shell: sh
  setup-maven-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: setup-maven
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: setup-maven/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Check format
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Check dist is up to date
        run: |
          npm run package
          git diff --exit-code -- dist
