name: Checks / envsubst
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
  pull_request:
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Render single template
        uses: jenseng/dynamic-uses@v1
        with:
          uses: hpedrorodrigues/actions/envsubst@${{ github.ref }}
          with: |
            {
              "template": ".github/extra/envsubst/simple.template.txt",
              "result": "result.txt"
            }
        env:
          NAME: World
      - name: Check result
        run: |
          [ 'Hello, World!' = "$(cat result.txt)" ]
      - name: Render multiple templates
        uses: jenseng/dynamic-uses@v1
        with:
          uses: hpedrorodrigues/actions/envsubst@${{ github.ref }}
          with: |
            {
              "template": ".github/extra/envsubst/simple.template.json .github/extra/envsubst/simple.template.md",
              "result": "result.json result.md"
            }
        env:
          JSON_VALUE: value
          TITLE: Awesome!
      - name: Check results
        run: |
          [ '{"key": "value"}' = "$(cat result.json)" ] && [ '# Awesome!' = "$(cat result.md)" ]
