name: Checks / envsubst
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
  pull_request:
    paths:
      - '.github/workflows/envsubst.yml'
      - 'envsubst/**'
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Render template
        uses: hpedrorodrigues/actions/envsubst@main
        with:
          template_file: .github/extra/template.txt
          result_file: result.txt
        env:
          NAME: World
      - name: Check result
        run: |
          [ 'Hello, World!' = "$(cat result.txt)" ]
